import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <img className='w-full h-80' src="/img/header.png" width={300} height={150} alt='' />
      <a href='/'><h1 className='text-6xl text-center p-5'>Blog Site</h1></a>
        {children}
      <img className='w-full h-20 pt-10' src="/img/footer.png" width={300} height={150} alt='' />
        </body>
      
    </html>
  )
}